---
title: "Clustering"
author: "Anton Holm"
date: '2022-03-24'
output: html_document
---

```{r}
source("..//full_method.R")
data_c250 <- readRDS("..//DE (250K genes, varying cellsize + cellshape)//(DATA) n = 57.000, c = 250, tissue = 400, VS.rdata")

statsc250 <- findStats(data_c250$Coordinates, k = 7, estimator = 2, track = TRUE)

saveRDS(statsc250, "PeakFinder Statistics c = 250.rdata")

statsc250 <- readRDS("PeakFinder Statistics c = 250.rdata")
plot(statsc250)
abline(v = 0.095)

clustersc250 <- clustering(statsc250, 0.095)

ggplot(data = NULL) +
  geom_point(aes(x = data_c250$Coordinates[,1], y = data_c250$Coordinates[,2], col = data_c250$Samples)) +
  geom_point(aes(x = data_c250$Coordinates[clustersc250$centerID, 1], y = data_c250$Coordinates[clustersc250$centerID ,2]), color = "red") +
  guides(col = "none")
```

```{r}
#Xie-Beni Index
cluster_points <- data_c250$Coordinates[clustersc250$centerID, ]
dist_to_peak <- dista(cluster_points, data_c250$Coordinates)
peak_to_peak <- dista(cluster_points, cluster_points)
prob_matrix <- clustersc250$assignments

xb <- sum(1/ncol(prob_matrix) * dist_to_peak * prob_matrix)/min(peak_to_peak[which(peak_to_peak > 0)])
xb

```


```{r}
sub_classes <- c("V1", "V2", "V3", "V4", "V5", "V6", "V7", "V8", "V9")
cluster_probsc250 <- as_tibble(cbind(t(clustersc250$assignments), data_c250$Coordinates)) %>% 
  rename("x" = V227, "y" = V228) %>% 
  gather(Class, Value, -c(x, y)) %>% 
  filter(Class %in% sub_classes)


centersc250 <- as_tibble(data_c250$Coordinates[clustersc250$centerID, ]) %>% 
  rename("x" = V1, "y" = V2)

ggplot(cluster_probsc250, aes(x = x, y = y, col = Value)) +
  geom_point() +
  facet_wrap(~Class) +
  scale_color_gradient(low = "blue", high = "red")
ggsave("5 Clustering visualized for large data.png")
```





















